/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.be.ac.umons.g02;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
